In [4]:
import tensorflow as tf
# tf.float32 자료형의 [?,3] 배열을 담을 수 있는 녀석을 준비
X = tf.placeholder(tf.float32,[None,3])
print(X)

Tensor("Placeholder:0", shape=(?, 3), dtype=float32)


In [32]:
# 들어갈 데이터 x
x_data  = [[1,2,3],[4,5,6]]
# (3,2)행렬 형태의 W 와 (2,1) 형태의 b 를 정규분포의 무작위 값으로 초기화 생성
W = tf.Variable(tf.random_normal([3,2]))
b = tf.Variable(tf.random_normal([2,1]))
# 행렬 곱셈인 tf.matmul함수 사용 / 단순 곱셈은 * or tf.mul 사용
expr = tf.matmul(X,W) + b

sess = tf.Session()
# 앞에서 정의한 변수들을 초기화 하는 함수
# 기존에 학습한 값들을 가져와서 사용하는 것이 아닌 처음 실행하는 것이라면 연산을 실행하기 전에 반드시 이 함수를 이용해 변수들을 초기화해야함
sess.run(tf.global_variables_initializer())

print("=== X_data ===")
print(x_data)
print("=== W ===")
print(sess.run(W))
print("=== b ===")
print(sess.run(b))
print("=== expr ===")
# print(sess.run(tf.matmul(X,W)))
print(sess.run(expr, feed_dict={X: x_data}))

sess.close()

=== X_data ===
[[1, 2, 3], [4, 5, 6]]
=== W ===
[[ 0.10107531  0.50408947]
 [-0.64099574  0.68007034]
 [ 0.40741187 -0.3802056 ]]
=== b ===
[[ 0.45281062]
 [-0.49072021]]
=== expr ===
[[ 0.4941301   1.17642403]
 [-0.84692639  2.64475608]]
